/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    MuTable: typeof import('@muyianking/table/index.js')['MuTable']
    MuTableColumn: typeof import('@muyianking/table/index.js')['MuTableColumn']
  }
}
